### ISSUE TITLE
请问能提供celebahq数据集上的预训练模型吗?

### ISSUE THREAD

**Issue by wangupupup** [xyfJASON/HCL#4]
请问能提供celebahq数据集上的预训练模型吗?

**Comment by xyfJASON** [comment]
The CelebA-HQ dataset was only used as the "noise content" for corruptions, not as the "background". Thus, we don't have a model pretrained on CelebA-HQ.

**Comment by wangupupup** [comment]
好的，明白了，谢谢回复！
